[package]
name = "rustaudio"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
libc = "0.2.177"
libpulse-binding = "2.30.1"
libpulse-simple-binding = "2.29.0"

[build-dependencies]
pkg-config = "0.3.32"
